apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups: [""]
    resources:
      - "metrics"
      - "nodes"
      - "nodes/metrics"
      - "nodes/stats"
      - "nodes/pods"
      - "nodes/proxy"
      - "pods"
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["batch"]
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
    resourceNames:
      - "cloudchipr"
      - "c8r"
      - "cloudchipr-agent"
      - "c8r-agent"
