apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  namespace: {{ include "..namespace" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or (not .Values.config.existingSecret) .Values.annotations }}
  annotations:
  {{- if not .Values.config.existingSecret }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
  {{- end }}
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "..serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: c8r-agent
        image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: C8R_CHART_VERSION
            value: {{ .Chart.Version | quote }}
        {{- with .Values.addEnv }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
          - secretRef:
              {{- if .Values.config.existingSecret }}
              name: {{ .Values.config.existingSecret }}
              {{- else }}
              name: {{ include "..fullname" . }}
              {{- end }}
          {{- with .Values.addEnvFrom }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
