apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  namespace: {{ include "..namespace" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "..fullname" . }}
      automountServiceAccountToken: true
      containers:
      - name: c8r-agent
        image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        envFrom:
          - secretRef:
              {{- if .Values.auth.existingSecret }}
              name: {{ .Values.auth.existingSecret }}
              {{- else }}
              name: {{ include "..fullname" . }}
              {{- end }}
