---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c8r-agent
  namespace: cloudchipr
  labels:
    app.kubernetes.io/name: c8r-agent
    app.kubernetes.io/instance: c8r-agent
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: c8r-agent
  labels:
    app.kubernetes.io/name: c8r-agent
    app.kubernetes.io/instance: c8r-agent
rules:
  - apiGroups: [""]
    resources:
      - "metrics"
      - "nodes"
      - "nodes/metrics"
      - "nodes/stats"
      - "nodes/pods"
      - "nodes/proxy"
      - "pods"
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["batch"]
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: c8r-agent
  labels:
    app.kubernetes.io/name: c8r-agent
    app.kubernetes.io/instance: c8r-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: c8r-agent
subjects:
  - kind: ServiceAccount
    name: c8r-agent
    namespace: cloudchipr

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: c8r-agent
  namespace: cloudchipr
  labels:
    app.kubernetes.io/name: c8r-agent
    app.kubernetes.io/instance: c8r-agent
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c8r-agent
  namespace: cloudchipr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c8r-agent
subjects:
  - kind: ServiceAccount
    name: c8r-agent
    namespace: cloudchipr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c8r-agent
  namespace: cloudchipr
  labels:
    app.kubernetes.io/name: c8r-agent
    app.kubernetes.io/instance: c8r-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: c8r-agent
      app.kubernetes.io/instance: c8r-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: c8r-agent
        app.kubernetes.io/instance: c8r-agent
    spec:
      serviceAccountName: c8r-agent
      automountServiceAccountToken: true
      containers:
        - name: c8r-agent
          image: quay.io/cloudchipr/c8r-agent:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 512Mi
            envFrom:
              - secretRef:
                  name: c8r-agent
